package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AjusteInventario generated by hbm2java
 */
@Entity
@Table(name="ajuste_inventario"
    ,catalog="gasisw_bd1"
)
public class AjusteInventario  implements java.io.Serializable {


     private Integer idAjusteInventario;
     private Date fecha;
     private String justificacion;
     private Set detaAjusteInventarios = new HashSet(0);

    public AjusteInventario() {
    }

    public AjusteInventario(Date fecha, String justificacion, Set detaAjusteInventarios) {
       this.fecha = fecha;
       this.justificacion = justificacion;
       this.detaAjusteInventarios = detaAjusteInventarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_ajuste_inventario", unique=true, nullable=false)
    public Integer getIdAjusteInventario() {
        return this.idAjusteInventario;
    }
    
    public void setIdAjusteInventario(Integer idAjusteInventario) {
        this.idAjusteInventario = idAjusteInventario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="justificacion", length=45)
    public String getJustificacion() {
        return this.justificacion;
    }
    
    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ajusteInventario")
    public Set getDetaAjusteInventarios() {
        return this.detaAjusteInventarios;
    }
    
    public void setDetaAjusteInventarios(Set detaAjusteInventarios) {
        this.detaAjusteInventarios = detaAjusteInventarios;
    }




}


