package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="gasisw_bd1"
)
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private Bodega bodega;
     private Character nombre;
     private String descripcion;
     private Set seccions = new HashSet(0);

    public Area() {
    }

	
    public Area(Bodega bodega) {
        this.bodega = bodega;
    }
    public Area(Bodega bodega, Character nombre, String descripcion, Set seccions) {
       this.bodega = bodega;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.seccions = seccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_area", unique=true, nullable=false)
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bodega_id_bodega", nullable=false)
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="nombre", length=1)
    public Character getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Character nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set getSeccions() {
        return this.seccions;
    }
    
    public void setSeccions(Set seccions) {
        this.seccions = seccions;
    }




}


