package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private Bodega bodega;
     private Character nombre;
     private String descripcion;
     private Set seccions = new HashSet(0);

    public Area() {
    }

	
    public Area(Bodega bodega) {
        this.bodega = bodega;
    }
    public Area(Bodega bodega, Character nombre, String descripcion, Set seccions) {
       this.bodega = bodega;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.seccions = seccions;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public Character getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Character nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSeccions() {
        return this.seccions;
    }
    
    public void setSeccions(Set seccions) {
        this.seccions = seccions;
    }




}


