package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bodega generated by hbm2java
 */
public class Bodega  implements java.io.Serializable {


     private Integer idBodega;
     private String nombre;
     private String descripcion;
     private Set areas = new HashSet(0);

    public Bodega() {
    }

    public Bodega(String nombre, String descripcion, Set areas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.areas = areas;
    }
   
    public Integer getIdBodega() {
        return this.idBodega;
    }
    
    public void setIdBodega(Integer idBodega) {
        this.idBodega = idBodega;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set areas) {
        this.areas = areas;
    }




}


