package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bomba generated by hbm2java
 */
@Entity
@Table(name="bomba"
    ,catalog="gasisw_bd1"
)
public class Bomba  implements java.io.Serializable {


     private Integer idBomba;
     private Combustible combustible;
     private Integer numero;
     private Set detaCombustibles = new HashSet(0);

    public Bomba() {
    }

	
    public Bomba(Combustible combustible) {
        this.combustible = combustible;
    }
    public Bomba(Combustible combustible, Integer numero, Set detaCombustibles) {
       this.combustible = combustible;
       this.numero = numero;
       this.detaCombustibles = detaCombustibles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_bomba", unique=true, nullable=false)
    public Integer getIdBomba() {
        return this.idBomba;
    }
    
    public void setIdBomba(Integer idBomba) {
        this.idBomba = idBomba;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMBUSTIBLE_id_combustible", nullable=false)
    public Combustible getCombustible() {
        return this.combustible;
    }
    
    public void setCombustible(Combustible combustible) {
        this.combustible = combustible;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bomba")
    public Set getDetaCombustibles() {
        return this.detaCombustibles;
    }
    
    public void setDetaCombustibles(Set detaCombustibles) {
        this.detaCombustibles = detaCombustibles;
    }




}


