package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bomba generated by hbm2java
 */
public class Bomba  implements java.io.Serializable {


     private Integer idBomba;
     private Combustible combustible;
     private Integer numero;
     private Set detaCombustibles = new HashSet(0);

    public Bomba() {
    }

	
    public Bomba(Combustible combustible) {
        this.combustible = combustible;
    }
    public Bomba(Combustible combustible, Integer numero, Set detaCombustibles) {
       this.combustible = combustible;
       this.numero = numero;
       this.detaCombustibles = detaCombustibles;
    }
   
    public Integer getIdBomba() {
        return this.idBomba;
    }
    
    public void setIdBomba(Integer idBomba) {
        this.idBomba = idBomba;
    }
    public Combustible getCombustible() {
        return this.combustible;
    }
    
    public void setCombustible(Combustible combustible) {
        this.combustible = combustible;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Set getDetaCombustibles() {
        return this.detaCombustibles;
    }
    
    public void setDetaCombustibles(Set detaCombustibles) {
        this.detaCombustibles = detaCombustibles;
    }




}


