package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,catalog="gasisw_bd1"
)
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombre;
     private String descripcion;
     private Set catProductos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nombre) {
        this.nombre = nombre;
    }
    public Categoria(String nombre, String descripcion, Set catProductos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.catProductos = catProductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_categoria", unique=true, nullable=false)
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="nombre", nullable=false, length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set getCatProductos() {
        return this.catProductos;
    }
    
    public void setCatProductos(Set catProductos) {
        this.catProductos = catProductos;
    }




}


