package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatProducto generated by hbm2java
 */
public class CatProducto  implements java.io.Serializable {


     private Integer idCatProducto;
     private Categoria categoria;
     private Marca marca;
     private Presentacion presentacion;
     private String nombre;
     private String descripcion;
     private Byte precio;
     private Set productoProveedors = new HashSet(0);
     private Set productos = new HashSet(0);
     private Set detaOrdenCompras = new HashSet(0);
     private Set detaOrdenVentas = new HashSet(0);

    public CatProducto() {
    }

	
    public CatProducto(Categoria categoria, Marca marca, Presentacion presentacion) {
        this.categoria = categoria;
        this.marca = marca;
        this.presentacion = presentacion;
    }
    public CatProducto(Categoria categoria, Marca marca, Presentacion presentacion, String nombre, String descripcion, Byte precio, Set productoProveedors, Set productos, Set detaOrdenCompras, Set detaOrdenVentas) {
       this.categoria = categoria;
       this.marca = marca;
       this.presentacion = presentacion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.productoProveedors = productoProveedors;
       this.productos = productos;
       this.detaOrdenCompras = detaOrdenCompras;
       this.detaOrdenVentas = detaOrdenVentas;
    }
   
    public Integer getIdCatProducto() {
        return this.idCatProducto;
    }
    
    public void setIdCatProducto(Integer idCatProducto) {
        this.idCatProducto = idCatProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Presentacion getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(Presentacion presentacion) {
        this.presentacion = presentacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Byte precio) {
        this.precio = precio;
    }
    public Set getProductoProveedors() {
        return this.productoProveedors;
    }
    
    public void setProductoProveedors(Set productoProveedors) {
        this.productoProveedors = productoProveedors;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    public Set getDetaOrdenCompras() {
        return this.detaOrdenCompras;
    }
    
    public void setDetaOrdenCompras(Set detaOrdenCompras) {
        this.detaOrdenCompras = detaOrdenCompras;
    }
    public Set getDetaOrdenVentas() {
        return this.detaOrdenVentas;
    }
    
    public void setDetaOrdenVentas(Set detaOrdenVentas) {
        this.detaOrdenVentas = detaOrdenVentas;
    }




}


