package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatProducto generated by hbm2java
 */
@Entity
@Table(name="cat_producto"
    ,catalog="gasisw_bd1"
)
public class CatProducto  implements java.io.Serializable {


     private Integer idCatProducto;
     private Categoria categoria;
     private Marca marca;
     private Presentacion presentacion;
     private String nombre;
     private String descripcion;
     private Byte precio;
     private Set productoProveedors = new HashSet(0);
     private Set productos = new HashSet(0);
     private Set detaOrdenCompras = new HashSet(0);
     private Set detaOrdenVentas = new HashSet(0);

    public CatProducto() {
        this.marca = new Marca();
        this.categoria = new Categoria();
        this.presentacion = new Presentacion();
    }

	
    public CatProducto(Categoria categoria, Marca marca, Presentacion presentacion) {
        this.categoria = categoria;
        this.marca = marca;
        this.presentacion = presentacion;
        this.precio = 0;
    }
    public CatProducto(Categoria categoria, Marca marca, Presentacion presentacion, String nombre, String descripcion, Byte precio, Set productoProveedors, Set productos, Set detaOrdenCompras, Set detaOrdenVentas) {
       this.categoria = categoria;
       this.marca = marca;
       this.presentacion = presentacion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.productoProveedors = productoProveedors;
       this.productos = productos;
       this.detaOrdenCompras = detaOrdenCompras;
       this.detaOrdenVentas = detaOrdenVentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cat_producto", unique=true, nullable=false)
    public Integer getIdCatProducto() {
        return this.idCatProducto;
    }
    
    public void setIdCatProducto(Integer idCatProducto) {
        this.idCatProducto = idCatProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria_id_categoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marca_id_marca", nullable=false)
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="presentacion_id_presentacion", nullable=false)
    public Presentacion getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(Presentacion presentacion) {
        this.presentacion = presentacion;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="precio", precision=2, scale=0)
    public Byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Byte precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catProducto")
    public Set getProductoProveedors() {
        return this.productoProveedors;
    }
    
    public void setProductoProveedors(Set productoProveedors) {
        this.productoProveedors = productoProveedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catProducto")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catProducto")
    public Set getDetaOrdenCompras() {
        return this.detaOrdenCompras;
    }
    
    public void setDetaOrdenCompras(Set detaOrdenCompras) {
        this.detaOrdenCompras = detaOrdenCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catProducto")
    public Set getDetaOrdenVentas() {
        return this.detaOrdenVentas;
    }
    
    public void setDetaOrdenVentas(Set detaOrdenVentas) {
        this.detaOrdenVentas = detaOrdenVentas;
    }




}


