package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * CierreCaja generated by hbm2java
 */
public class CierreCaja  implements java.io.Serializable {


     private Integer idCierreCaja;
     private Empleado empleado;
     private Byte saldoApertura;
     private Byte saldoCierre;
     private Integer centavo;
     private Integer diez;
     private Integer cuarto;
     private Integer dolar;
     private Integer cincoD;
     private Integer diezD;
     private Integer veinteD;
     private Byte montoEfectivo;
     private Byte montoVoucher;
     private Byte montoCheque;

    public CierreCaja() {
    }

	
    public CierreCaja(Empleado empleado) {
        this.empleado = empleado;
    }
    public CierreCaja(Empleado empleado, Byte saldoApertura, Byte saldoCierre, Integer centavo, Integer diez, Integer cuarto, Integer dolar, Integer cincoD, Integer diezD, Integer veinteD, Byte montoEfectivo, Byte montoVoucher, Byte montoCheque) {
       this.empleado = empleado;
       this.saldoApertura = saldoApertura;
       this.saldoCierre = saldoCierre;
       this.centavo = centavo;
       this.diez = diez;
       this.cuarto = cuarto;
       this.dolar = dolar;
       this.cincoD = cincoD;
       this.diezD = diezD;
       this.veinteD = veinteD;
       this.montoEfectivo = montoEfectivo;
       this.montoVoucher = montoVoucher;
       this.montoCheque = montoCheque;
    }
   
    public Integer getIdCierreCaja() {
        return this.idCierreCaja;
    }
    
    public void setIdCierreCaja(Integer idCierreCaja) {
        this.idCierreCaja = idCierreCaja;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Byte getSaldoApertura() {
        return this.saldoApertura;
    }
    
    public void setSaldoApertura(Byte saldoApertura) {
        this.saldoApertura = saldoApertura;
    }
    public Byte getSaldoCierre() {
        return this.saldoCierre;
    }
    
    public void setSaldoCierre(Byte saldoCierre) {
        this.saldoCierre = saldoCierre;
    }
    public Integer getCentavo() {
        return this.centavo;
    }
    
    public void setCentavo(Integer centavo) {
        this.centavo = centavo;
    }
    public Integer getDiez() {
        return this.diez;
    }
    
    public void setDiez(Integer diez) {
        this.diez = diez;
    }
    public Integer getCuarto() {
        return this.cuarto;
    }
    
    public void setCuarto(Integer cuarto) {
        this.cuarto = cuarto;
    }
    public Integer getDolar() {
        return this.dolar;
    }
    
    public void setDolar(Integer dolar) {
        this.dolar = dolar;
    }
    public Integer getCincoD() {
        return this.cincoD;
    }
    
    public void setCincoD(Integer cincoD) {
        this.cincoD = cincoD;
    }
    public Integer getDiezD() {
        return this.diezD;
    }
    
    public void setDiezD(Integer diezD) {
        this.diezD = diezD;
    }
    public Integer getVeinteD() {
        return this.veinteD;
    }
    
    public void setVeinteD(Integer veinteD) {
        this.veinteD = veinteD;
    }
    public Byte getMontoEfectivo() {
        return this.montoEfectivo;
    }
    
    public void setMontoEfectivo(Byte montoEfectivo) {
        this.montoEfectivo = montoEfectivo;
    }
    public Byte getMontoVoucher() {
        return this.montoVoucher;
    }
    
    public void setMontoVoucher(Byte montoVoucher) {
        this.montoVoucher = montoVoucher;
    }
    public Byte getMontoCheque() {
        return this.montoCheque;
    }
    
    public void setMontoCheque(Byte montoCheque) {
        this.montoCheque = montoCheque;
    }




}


