package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Combustible generated by hbm2java
 */
public class Combustible  implements java.io.Serializable {


     private Integer idCombustible;
     private String nombre;
     private Byte cantidad;
     private Set bombas = new HashSet(0);

    public Combustible() {
    }

    public Combustible(String nombre, Byte cantidad, Set bombas) {
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.bombas = bombas;
    }
   
    public Integer getIdCombustible() {
        return this.idCombustible;
    }
    
    public void setIdCombustible(Integer idCombustible) {
        this.idCombustible = idCombustible;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Byte getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Byte cantidad) {
        this.cantidad = cantidad;
    }
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }




}


