package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Combustible generated by hbm2java
 */
@Entity
@Table(name="combustible"
    ,catalog="gasisw_bd1"
)
public class Combustible  implements java.io.Serializable {


     private Integer idCombustible;
     private String nombre;
     private Byte cantidad;
     private Set bombas = new HashSet(0);

    public Combustible() {
    }

    public Combustible(String nombre, Byte cantidad, Set bombas) {
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.bombas = bombas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_combustible", unique=true, nullable=false)
    public Integer getIdCombustible() {
        return this.idCombustible;
    }
    
    public void setIdCombustible(Integer idCombustible) {
        this.idCombustible = idCombustible;
    }

    
    @Column(name="nombre", length=15)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="cantidad", precision=2, scale=0)
    public Byte getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Byte cantidad) {
        this.cantidad = cantidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="combustible")
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }




}


