package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="gasisw_bd1"
)
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Date fechaHora;
     private String correlativo;
     private Set productos = new HashSet(0);

    public Compra() {
    }

	
    public Compra(String correlativo) {
        this.correlativo = correlativo;
    }
    public Compra(Date fechaHora, String correlativo, Set productos) {
       this.fechaHora = fechaHora;
       this.correlativo = correlativo;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_compra", unique=true, nullable=false)
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_hora", length=19)
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    
    @Column(name="correlativo", nullable=false, length=45)
    public String getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(String correlativo) {
        this.correlativo = correlativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compra")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


