package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * DetaOrdenCompra generated by hbm2java
 */
public class DetaOrdenCompra  implements java.io.Serializable {


     private Integer idDetaOrdenCompra;
     private CatProducto catProducto;
     private OrdenCompra ordenCompra;
     private Byte precio;
     private Integer cantidad;

    public DetaOrdenCompra() {
    }

	
    public DetaOrdenCompra(CatProducto catProducto, OrdenCompra ordenCompra) {
        this.catProducto = catProducto;
        this.ordenCompra = ordenCompra;
    }
    public DetaOrdenCompra(CatProducto catProducto, OrdenCompra ordenCompra, Byte precio, Integer cantidad) {
       this.catProducto = catProducto;
       this.ordenCompra = ordenCompra;
       this.precio = precio;
       this.cantidad = cantidad;
    }
   
    public Integer getIdDetaOrdenCompra() {
        return this.idDetaOrdenCompra;
    }
    
    public void setIdDetaOrdenCompra(Integer idDetaOrdenCompra) {
        this.idDetaOrdenCompra = idDetaOrdenCompra;
    }
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }
    public OrdenCompra getOrdenCompra() {
        return this.ordenCompra;
    }
    
    public void setOrdenCompra(OrdenCompra ordenCompra) {
        this.ordenCompra = ordenCompra;
    }
    public Byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Byte precio) {
        this.precio = precio;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


