package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * DetaOrdenVenta generated by hbm2java
 */
public class DetaOrdenVenta  implements java.io.Serializable {


     private Integer idOrdenVenta;
     private CatProducto catProducto;
     private OrdenVenta ordenVenta;
     private Byte precio;
     private Integer cantidad;

    public DetaOrdenVenta() {
    }

	
    public DetaOrdenVenta(CatProducto catProducto, OrdenVenta ordenVenta) {
        this.catProducto = catProducto;
        this.ordenVenta = ordenVenta;
    }
    public DetaOrdenVenta(CatProducto catProducto, OrdenVenta ordenVenta, Byte precio, Integer cantidad) {
       this.catProducto = catProducto;
       this.ordenVenta = ordenVenta;
       this.precio = precio;
       this.cantidad = cantidad;
    }
   
    public Integer getIdOrdenVenta() {
        return this.idOrdenVenta;
    }
    
    public void setIdOrdenVenta(Integer idOrdenVenta) {
        this.idOrdenVenta = idOrdenVenta;
    }
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }
    public OrdenVenta getOrdenVenta() {
        return this.ordenVenta;
    }
    
    public void setOrdenVenta(OrdenVenta ordenVenta) {
        this.ordenVenta = ordenVenta;
    }
    public Byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Byte precio) {
        this.precio = precio;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


