package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetaOrdenVenta generated by hbm2java
 */
@Entity
@Table(name="deta_orden_venta"
    ,catalog="gasisw_bd1"
)
public class DetaOrdenVenta  implements java.io.Serializable {


     private Integer idOrdenVenta;
     private CatProducto catProducto;
     private OrdenVenta ordenVenta;
     private Byte precio;
     private Integer cantidad;

    public DetaOrdenVenta() {
    }

	
    public DetaOrdenVenta(CatProducto catProducto, OrdenVenta ordenVenta) {
        this.catProducto = catProducto;
        this.ordenVenta = ordenVenta;
    }
    public DetaOrdenVenta(CatProducto catProducto, OrdenVenta ordenVenta, Byte precio, Integer cantidad) {
       this.catProducto = catProducto;
       this.ordenVenta = ordenVenta;
       this.precio = precio;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_orden_venta", unique=true, nullable=false)
    public Integer getIdOrdenVenta() {
        return this.idOrdenVenta;
    }
    
    public void setIdOrdenVenta(Integer idOrdenVenta) {
        this.idOrdenVenta = idOrdenVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_producto_id_cat_producto", nullable=false)
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orden_venta_id_orden_venta", nullable=false)
    public OrdenVenta getOrdenVenta() {
        return this.ordenVenta;
    }
    
    public void setOrdenVenta(OrdenVenta ordenVenta) {
        this.ordenVenta = ordenVenta;
    }

    
    @Column(name="precio", precision=2, scale=0)
    public Byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Byte precio) {
        this.precio = precio;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


