package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetaCombustible generated by hbm2java
 */
@Entity
@Table(name="deta_combustible"
    ,catalog="gasisw_bd1"
)
public class DetaCombustible  implements java.io.Serializable {


     private Integer idDetaCombustible;
     private Bomba bomba;
     private String cantidad;
     private String monto;
     private Set facturas = new HashSet(0);

    public DetaCombustible() {
    }

	
    public DetaCombustible(Bomba bomba) {
        this.bomba = bomba;
    }
    public DetaCombustible(Bomba bomba, String cantidad, String monto, Set facturas) {
       this.bomba = bomba;
       this.cantidad = cantidad;
       this.monto = monto;
       this.facturas = facturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_deta_combustible", unique=true, nullable=false)
    public Integer getIdDetaCombustible() {
        return this.idDetaCombustible;
    }
    
    public void setIdDetaCombustible(Integer idDetaCombustible) {
        this.idDetaCombustible = idDetaCombustible;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Bomba_id_bomba", nullable=false)
    public Bomba getBomba() {
        return this.bomba;
    }
    
    public void setBomba(Bomba bomba) {
        this.bomba = bomba;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="monto", length=45)
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detaCombustible")
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


