package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * DetaAjusteInventario generated by hbm2java
 */
public class DetaAjusteInventario  implements java.io.Serializable {


     private Integer idDetaAjusteInventario;
     private AjusteInventario ajusteInventario;
     private Producto producto;

    public DetaAjusteInventario() {
    }

    public DetaAjusteInventario(AjusteInventario ajusteInventario, Producto producto) {
       this.ajusteInventario = ajusteInventario;
       this.producto = producto;
    }
   
    public Integer getIdDetaAjusteInventario() {
        return this.idDetaAjusteInventario;
    }
    
    public void setIdDetaAjusteInventario(Integer idDetaAjusteInventario) {
        this.idDetaAjusteInventario = idDetaAjusteInventario;
    }
    public AjusteInventario getAjusteInventario() {
        return this.ajusteInventario;
    }
    
    public void setAjusteInventario(AjusteInventario ajusteInventario) {
        this.ajusteInventario = ajusteInventario;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }




}


