package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DetaCombustible generated by hbm2java
 */
public class DetaCombustible  implements java.io.Serializable {


     private Integer idDetaCombustible;
     private Bomba bomba;
     private String cantidad;
     private String monto;
     private Set facturas = new HashSet(0);

    public DetaCombustible() {
    }

	
    public DetaCombustible(Bomba bomba) {
        this.bomba = bomba;
    }
    public DetaCombustible(Bomba bomba, String cantidad, String monto, Set facturas) {
       this.bomba = bomba;
       this.cantidad = cantidad;
       this.monto = monto;
       this.facturas = facturas;
    }
   
    public Integer getIdDetaCombustible() {
        return this.idDetaCombustible;
    }
    
    public void setIdDetaCombustible(Integer idDetaCombustible) {
        this.idDetaCombustible = idDetaCombustible;
    }
    public Bomba getBomba() {
        return this.bomba;
    }
    
    public void setBomba(Bomba bomba) {
        this.bomba = bomba;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


