package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetFactura generated by hbm2java
 */
@Entity
@Table(name="det_factura"
    ,catalog="gasisw_bd1"
)
public class DetFactura  implements java.io.Serializable {


     private Integer idDetaFactura;
     private Factura factura;
     private Producto producto;
     private Byte precio;

    public DetFactura() {
    }

	
    public DetFactura(Factura factura, Producto producto) {
        this.factura = factura;
        this.producto = producto;
    }
    public DetFactura(Factura factura, Producto producto, Byte precio) {
       this.factura = factura;
       this.producto = producto;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_deta_factura", unique=true, nullable=false)
    public Integer getIdDetaFactura() {
        return this.idDetaFactura;
    }
    
    public void setIdDetaFactura(Integer idDetaFactura) {
        this.idDetaFactura = idDetaFactura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="factura_id_factura", nullable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="producto_id_producto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="precio", precision=2, scale=0)
    public Byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Byte precio) {
        this.precio = precio;
    }




}


