package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * DetFactura generated by hbm2java
 */
public class DetFactura  implements java.io.Serializable {


     private Integer idDetaFactura;
     private Factura factura;
     private Producto producto;
     private Byte precio;

    public DetFactura() {
    }

	
    public DetFactura(Factura factura, Producto producto) {
        this.factura = factura;
        this.producto = producto;
    }
    public DetFactura(Factura factura, Producto producto, Byte precio) {
       this.factura = factura;
       this.producto = producto;
       this.precio = precio;
    }
   
    public Integer getIdDetaFactura() {
        return this.idDetaFactura;
    }
    
    public void setIdDetaFactura(Integer idDetaFactura) {
        this.idDetaFactura = idDetaFactura;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Byte precio) {
        this.precio = precio;
    }




}


