package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="gasisw_bd1"
)
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombre;
     private String apellido;
     private String dui;
     private Set cierreCajas = new HashSet(0);
     private Set ordenCompras = new HashSet(0);
     private Set ordenVentas = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String nombre, String apellido, String dui) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.dui = dui;
    }
    public Empleado(String nombre, String apellido, String dui, Set cierreCajas, Set ordenCompras, Set ordenVentas, Set usuarios, Set facturas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dui = dui;
       this.cierreCajas = cierreCajas;
       this.ordenCompras = ordenCompras;
       this.ordenVentas = ordenVentas;
       this.usuarios = usuarios;
       this.facturas = facturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_empleado", unique=true, nullable=false)
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="dui", nullable=false, length=10)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getCierreCajas() {
        return this.cierreCajas;
    }
    
    public void setCierreCajas(Set cierreCajas) {
        this.cierreCajas = cierreCajas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getOrdenCompras() {
        return this.ordenCompras;
    }
    
    public void setOrdenCompras(Set ordenCompras) {
        this.ordenCompras = ordenCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getOrdenVentas() {
        return this.ordenVentas;
    }
    
    public void setOrdenVentas(Set ordenVentas) {
        this.ordenVentas = ordenVentas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


