package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombre;
     private String apellido;
     private String dui;
     private Set cierreCajas = new HashSet(0);
     private Set ordenCompras = new HashSet(0);
     private Set ordenVentas = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Empleado() {
        this.idEmpleado=0;
    }

	
    public Empleado(String nombre, String apellido, String dui) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.dui = dui;
    }
    public Empleado(String nombre, String apellido, String dui, Set cierreCajas, Set ordenCompras, Set ordenVentas, Set usuarios, Set facturas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dui = dui;
       this.cierreCajas = cierreCajas;
       this.ordenCompras = ordenCompras;
       this.ordenVentas = ordenVentas;
       this.usuarios = usuarios;
       this.facturas = facturas;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public Set getCierreCajas() {
        return this.cierreCajas;
    }
    
    public void setCierreCajas(Set cierreCajas) {
        this.cierreCajas = cierreCajas;
    }
    public Set getOrdenCompras() {
        return this.ordenCompras;
    }
    
    public void setOrdenCompras(Set ordenCompras) {
        this.ordenCompras = ordenCompras;
    }
    public Set getOrdenVentas() {
        return this.ordenVentas;
    }
    
    public void setOrdenVentas(Set ordenVentas) {
        this.ordenVentas = ordenVentas;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


