package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private DetaCombustible detaCombustible;
     private Empleado empleado;
     private TipoFactura tipoFactura;
     private String correlativo;
     private Date fechaHora;
     private Long ivaAplicado;
     private Set detFacturas = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente, DetaCombustible detaCombustible, Empleado empleado, TipoFactura tipoFactura, String correlativo) {
        this.cliente = cliente;
        this.detaCombustible = detaCombustible;
        this.empleado = empleado;
        this.tipoFactura = tipoFactura;
        this.correlativo = correlativo;
    }
    public Factura(Cliente cliente, DetaCombustible detaCombustible, Empleado empleado, TipoFactura tipoFactura, String correlativo, Date fechaHora, Long ivaAplicado, Set detFacturas, Set pagos) {
       this.cliente = cliente;
       this.detaCombustible = detaCombustible;
       this.empleado = empleado;
       this.tipoFactura = tipoFactura;
       this.correlativo = correlativo;
       this.fechaHora = fechaHora;
       this.ivaAplicado = ivaAplicado;
       this.detFacturas = detFacturas;
       this.pagos = pagos;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public DetaCombustible getDetaCombustible() {
        return this.detaCombustible;
    }
    
    public void setDetaCombustible(DetaCombustible detaCombustible) {
        this.detaCombustible = detaCombustible;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public TipoFactura getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(TipoFactura tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public String getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(String correlativo) {
        this.correlativo = correlativo;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Long getIvaAplicado() {
        return this.ivaAplicado;
    }
    
    public void setIvaAplicado(Long ivaAplicado) {
        this.ivaAplicado = ivaAplicado;
    }
    public Set getDetFacturas() {
        return this.detFacturas;
    }
    
    public void setDetFacturas(Set detFacturas) {
        this.detFacturas = detFacturas;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


