package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="factura"
    ,catalog="gasisw_bd1"
)
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private DetaCombustible detaCombustible;
     private Empleado empleado;
     private TipoFactura tipoFactura;
     private String correlativo;
     private Date fechaHora;
     private Long ivaAplicado;
     private Set detFacturas = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente, DetaCombustible detaCombustible, Empleado empleado, TipoFactura tipoFactura, String correlativo) {
        this.cliente = cliente;
        this.detaCombustible = detaCombustible;
        this.empleado = empleado;
        this.tipoFactura = tipoFactura;
        this.correlativo = correlativo;
    }
    public Factura(Cliente cliente, DetaCombustible detaCombustible, Empleado empleado, TipoFactura tipoFactura, String correlativo, Date fechaHora, Long ivaAplicado, Set detFacturas, Set pagos) {
       this.cliente = cliente;
       this.detaCombustible = detaCombustible;
       this.empleado = empleado;
       this.tipoFactura = tipoFactura;
       this.correlativo = correlativo;
       this.fechaHora = fechaHora;
       this.ivaAplicado = ivaAplicado;
       this.detFacturas = detFacturas;
       this.pagos = pagos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_factura", unique=true, nullable=false)
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DETA_COMBUSTIBLE_id_deta_combustible", nullable=false)
    public DetaCombustible getDetaCombustible() {
        return this.detaCombustible;
    }
    
    public void setDetaCombustible(DetaCombustible detaCombustible) {
        this.detaCombustible = detaCombustible;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empleado_id_empleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_factura_id_tipo_factura", nullable=false)
    public TipoFactura getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(TipoFactura tipoFactura) {
        this.tipoFactura = tipoFactura;
    }

    
    @Column(name="correlativo", nullable=false, length=10)
    public String getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(String correlativo) {
        this.correlativo = correlativo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_hora", length=19)
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    
    @Column(name="iva_aplicado", precision=10, scale=0)
    public Long getIvaAplicado() {
        return this.ivaAplicado;
    }
    
    public void setIvaAplicado(Long ivaAplicado) {
        this.ivaAplicado = ivaAplicado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="factura")
    public Set getDetFacturas() {
        return this.detFacturas;
    }
    
    public void setDetFacturas(Set detFacturas) {
        this.detFacturas = detFacturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="factura")
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


