package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GeneralParameters generated by hbm2java
 */
public class GeneralParameters  implements java.io.Serializable {


     private Integer idParameter;
     private String lookupCode;
     private String meaning;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private int creadoPor;
     private int modificadoPor;

    public GeneralParameters() {
    }

	
    public GeneralParameters(String lookupCode, String meaning, Date fechaCreacion, Date fechaModificacion, int creadoPor, int modificadoPor) {
        this.lookupCode = lookupCode;
        this.meaning = meaning;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.creadoPor = creadoPor;
        this.modificadoPor = modificadoPor;
    }
    public GeneralParameters(String lookupCode, String meaning, String descripcion, Date fechaCreacion, Date fechaModificacion, int creadoPor, int modificadoPor) {
       this.lookupCode = lookupCode;
       this.meaning = meaning;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
    }
   
    public Integer getIdParameter() {
        return this.idParameter;
    }
    
    public void setIdParameter(Integer idParameter) {
        this.idParameter = idParameter;
    }
    public String getLookupCode() {
        return this.lookupCode;
    }
    
    public void setLookupCode(String lookupCode) {
        this.lookupCode = lookupCode;
    }
    public String getMeaning() {
        return this.meaning;
    }
    
    public void setMeaning(String meaning) {
        this.meaning = meaning;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public int getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(int creadoPor) {
        this.creadoPor = creadoPor;
    }
    public int getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(int modificadoPor) {
        this.modificadoPor = modificadoPor;
    }




}


