package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LecturaSensor generated by hbm2java
 */
public class LecturaSensor  implements java.io.Serializable {


     private Integer idlecturaSensor;
     private Date fechaLectura;
     private float temperatura;
     private float humAmbiente;
     private float humTerreno;
     private float lux;

    public LecturaSensor() {
    }

    public LecturaSensor(Date fechaLectura, float temperatura, float humAmbiente, float humTerreno, float lux) {
       this.fechaLectura = fechaLectura;
       this.temperatura = temperatura;
       this.humAmbiente = humAmbiente;
       this.humTerreno = humTerreno;
       this.lux = lux;
    }
   
    public Integer getIdlecturaSensor() {
        return this.idlecturaSensor;
    }
    
    public void setIdlecturaSensor(Integer idlecturaSensor) {
        this.idlecturaSensor = idlecturaSensor;
    }
    public Date getFechaLectura() {
        return this.fechaLectura;
    }
    
    public void setFechaLectura(Date fechaLectura) {
        this.fechaLectura = fechaLectura;
    }
    public float getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(float temperatura) {
        this.temperatura = temperatura;
    }
    public float getHumAmbiente() {
        return this.humAmbiente;
    }
    
    public void setHumAmbiente(float humAmbiente) {
        this.humAmbiente = humAmbiente;
    }
    public float getHumTerreno() {
        return this.humTerreno;
    }
    
    public void setHumTerreno(float humTerreno) {
        this.humTerreno = humTerreno;
    }
    public float getLux() {
        return this.lux;
    }
    
    public void setLux(float lux) {
        this.lux = lux;
    }




}


