package model;
// Generated 10-20-2015 11:47:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="gasisw_bd"
)
public class Menu  implements java.io.Serializable {


     private Integer idmenu;
     private int nivel;
     private int orden;
     private String nombre;
     private String url;
     private String icono;
     private String estado;
     private Set rolMenus = new HashSet(0);

    public Menu() {
    }

	
    public Menu(int nivel, int orden, String nombre, String estado) {
        this.nivel = nivel;
        this.orden = orden;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Menu(int nivel, int orden, String nombre, String url, String icono, String estado, Set rolMenus) {
       this.nivel = nivel;
       this.orden = orden;
       this.nombre = nombre;
       this.url = url;
       this.icono = icono;
       this.estado = estado;
       this.rolMenus = rolMenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmenu", unique=true, nullable=false)
    public Integer getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(Integer idmenu) {
        this.idmenu = idmenu;
    }

    
    @Column(name="nivel", nullable=false)
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="orden", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

    
    @Column(name="nombre", nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="url", length=120)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="icono", length=45)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menu")
    public Set getRolMenus() {
        return this.rolMenus;
    }
    
    public void setRolMenus(Set rolMenus) {
        this.rolMenus = rolMenus;
    }




}


