package model;
// Generated 12-09-2015 09:53:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="gasisw_bd1"
)
public class Menu  implements java.io.Serializable {


     private Integer idmenu;
     private String nombre;
     private String estado;
     private Integer orden;
     private String url;
     private Set rolMenus = new HashSet(0);
     private Set submenus = new HashSet(0);

    public Menu() {
    }

	
    public Menu(String nombre, String estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Menu(String nombre, String estado, Integer orden, String url, Set rolMenus, Set submenus) {
       this.nombre = nombre;
       this.estado = estado;
       this.orden = orden;
       this.url = url;
       this.rolMenus = rolMenus;
       this.submenus = submenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmenu", unique=true, nullable=false)
    public Integer getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(Integer idmenu) {
        this.idmenu = idmenu;
    }

    
    @Column(name="nombre", nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="orden")
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    
    @Column(name="url", length=240)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menu")
    public Set getRolMenus() {
        return this.rolMenus;
    }
    
    public void setRolMenus(Set rolMenus) {
        this.rolMenus = rolMenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menu")
    public Set getSubmenus() {
        return this.submenus;
    }
    
    public void setSubmenus(Set submenus) {
        this.submenus = submenus;
    }




}


