package model;
// Generated 06-29-2016 08:46:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer idmenu;
     private Icono icono;
     private String nombre;
     private String estado;
     private Integer orden;
     private String url;
     private Set rolMenus = new HashSet(0);
     private Set submenus = new HashSet(0);

    public Menu() {
    }

	
    public Menu(String nombre, String estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Menu(Icono icono, String nombre, String estado, Integer orden, String url, Set rolMenus, Set submenus) {
       this.icono = icono;
       this.nombre = nombre;
       this.estado = estado;
       this.orden = orden;
       this.url = url;
       this.rolMenus = rolMenus;
       this.submenus = submenus;
    }
   
    public Integer getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(Integer idmenu) {
        this.idmenu = idmenu;
    }
    public Icono getIcono() {
        return this.icono;
    }
    
    public void setIcono(Icono icono) {
        this.icono = icono;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getRolMenus() {
        return this.rolMenus;
    }
    
    public void setRolMenus(Set rolMenus) {
        this.rolMenus = rolMenus;
    }
    public Set getSubmenus() {
        return this.submenus;
    }
    
    public void setSubmenus(Set submenus) {
        this.submenus = submenus;
    }




}


