package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private Departamento departamento;
     private String nombre;
     private Set clientes = new HashSet(0);
     private Set proveedors = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(Departamento departamento, String nombre) {
        this.departamento = departamento;
        this.nombre = nombre;
    }
    public Municipio(Departamento departamento, String nombre, Set clientes, Set proveedors) {
       this.departamento = departamento;
       this.nombre = nombre;
       this.clientes = clientes;
       this.proveedors = proveedors;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set proveedors) {
        this.proveedors = proveedors;
    }




}


