package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenVenta generated by hbm2java
 */
public class OrdenVenta  implements java.io.Serializable {


     private int idOrdenVenta;
     private Cliente cliente;
     private Empleado empleado;
     private Date fecha;
     private Date fechaVence;
     private Date fechaEntrega;
     private Set detaOrdenVentas = new HashSet(0);

    public OrdenVenta() {
    }

	
    public OrdenVenta(int idOrdenVenta, Cliente cliente, Empleado empleado, Date fecha) {
        this.idOrdenVenta = idOrdenVenta;
        this.cliente = cliente;
        this.empleado = empleado;
        this.fecha = fecha;
    }
    public OrdenVenta(int idOrdenVenta, Cliente cliente, Empleado empleado, Date fecha, Date fechaVence, Date fechaEntrega, Set detaOrdenVentas) {
       this.idOrdenVenta = idOrdenVenta;
       this.cliente = cliente;
       this.empleado = empleado;
       this.fecha = fecha;
       this.fechaVence = fechaVence;
       this.fechaEntrega = fechaEntrega;
       this.detaOrdenVentas = detaOrdenVentas;
    }
   
    public int getIdOrdenVenta() {
        return this.idOrdenVenta;
    }
    
    public void setIdOrdenVenta(int idOrdenVenta) {
        this.idOrdenVenta = idOrdenVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Set getDetaOrdenVentas() {
        return this.detaOrdenVentas;
    }
    
    public void setDetaOrdenVentas(Set detaOrdenVentas) {
        this.detaOrdenVentas = detaOrdenVentas;
    }




}


