package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenCompra generated by hbm2java
 */
@Entity
@Table(name="orden_compra"
    ,catalog="gasisw_bd1"
)
public class OrdenCompra  implements java.io.Serializable {


     private Integer idOrden;
     private Empleado empleado;
     private Proveedor proveedor;
     private Date fecha;
     private Date fechaVence;
     private Date fechaEntrega;
     private Set detaOrdenCompras = new HashSet(0);

    public OrdenCompra() {
    }

	
    public OrdenCompra(Empleado empleado, Proveedor proveedor) {
        this.empleado = empleado;
        this.proveedor = proveedor;
    }
    public OrdenCompra(Empleado empleado, Proveedor proveedor, Date fecha, Date fechaVence, Date fechaEntrega, Set detaOrdenCompras) {
       this.empleado = empleado;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.fechaVence = fechaVence;
       this.fechaEntrega = fechaEntrega;
       this.detaOrdenCompras = detaOrdenCompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_orden", unique=true, nullable=false)
    public Integer getIdOrden() {
        return this.idOrden;
    }
    
    public void setIdOrden(Integer idOrden) {
        this.idOrden = idOrden;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empleado_id_empleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor_id_proveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_vence", length=10)
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_entrega", length=10)
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenCompra")
    public Set getDetaOrdenCompras() {
        return this.detaOrdenCompras;
    }
    
    public void setDetaOrdenCompras(Set detaOrdenCompras) {
        this.detaOrdenCompras = detaOrdenCompras;
    }




}


