package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenVenta generated by hbm2java
 */
@Entity
@Table(name="orden_venta"
    ,catalog="gasisw_bd1"
)
public class OrdenVenta  implements java.io.Serializable {


     private int idOrdenVenta;
     private Cliente cliente;
     private Empleado empleado;
     private Date fecha;
     private Date fechaVence;
     private Date fechaEntrega;
     private Set detaOrdenVentas = new HashSet(0);

    public OrdenVenta() {
    }

	
    public OrdenVenta(int idOrdenVenta, Cliente cliente, Empleado empleado, Date fecha) {
        this.idOrdenVenta = idOrdenVenta;
        this.cliente = cliente;
        this.empleado = empleado;
        this.fecha = fecha;
    }
    public OrdenVenta(int idOrdenVenta, Cliente cliente, Empleado empleado, Date fecha, Date fechaVence, Date fechaEntrega, Set detaOrdenVentas) {
       this.idOrdenVenta = idOrdenVenta;
       this.cliente = cliente;
       this.empleado = empleado;
       this.fecha = fecha;
       this.fechaVence = fechaVence;
       this.fechaEntrega = fechaEntrega;
       this.detaOrdenVentas = detaOrdenVentas;
    }
   
     @Id 

    
    @Column(name="id_orden_venta", unique=true, nullable=false)
    public int getIdOrdenVenta() {
        return this.idOrdenVenta;
    }
    
    public void setIdOrdenVenta(int idOrdenVenta) {
        this.idOrdenVenta = idOrdenVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empleado_id_empleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_vence", length=10)
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_entrega", length=10)
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenVenta")
    public Set getDetaOrdenVentas() {
        return this.detaOrdenVentas;
    }
    
    public void setDetaOrdenVentas(Set detaOrdenVentas) {
        this.detaOrdenVentas = detaOrdenVentas;
    }




}


