package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenCompra generated by hbm2java
 */
public class OrdenCompra  implements java.io.Serializable {


     private Integer idOrden;
     private Empleado empleado;
     private Proveedor proveedor;
     private Date fecha;
     private Date fechaVence;
     private Date fechaEntrega;
     private Set detaOrdenCompras = new HashSet(0);

    public OrdenCompra() {
    }

	
    public OrdenCompra(Empleado empleado, Proveedor proveedor) {
        this.empleado = empleado;
        this.proveedor = proveedor;
    }
    public OrdenCompra(Empleado empleado, Proveedor proveedor, Date fecha, Date fechaVence, Date fechaEntrega, Set detaOrdenCompras) {
       this.empleado = empleado;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.fechaVence = fechaVence;
       this.fechaEntrega = fechaEntrega;
       this.detaOrdenCompras = detaOrdenCompras;
    }
   
    public Integer getIdOrden() {
        return this.idOrden;
    }
    
    public void setIdOrden(Integer idOrden) {
        this.idOrden = idOrden;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Set getDetaOrdenCompras() {
        return this.detaOrdenCompras;
    }
    
    public void setDetaOrdenCompras(Set detaOrdenCompras) {
        this.detaOrdenCompras = detaOrdenCompras;
    }




}


