package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer idPago;
     private Factura factura;
     private TipoPago tipoPago;

    public Pago() {
    }

    public Pago(Factura factura, TipoPago tipoPago) {
       this.factura = factura;
       this.tipoPago = tipoPago;
    }
   
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }




}


