package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Presentacion generated by hbm2java
 */
public class Presentacion  implements java.io.Serializable {


     private Integer idPresentacion;
     private String nombre;
     private String descripcion;
     private Set catProductos = new HashSet(0);

    public Presentacion() {
    }

    public Presentacion(String nombre, String descripcion, Set catProductos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.catProductos = catProductos;
    }
   
    public Integer getIdPresentacion() {
        return this.idPresentacion;
    }
    
    public void setIdPresentacion(Integer idPresentacion) {
        this.idPresentacion = idPresentacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCatProductos() {
        return this.catProductos;
    }
    
    public void setCatProductos(Set catProductos) {
        this.catProductos = catProductos;
    }




}


