package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="gasisw_bd1"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private CatProducto catProducto;
     private Compra compra;
     private Seccion seccion;
     private int codBarra;
     private char estado;
     private Set detFacturas = new HashSet(0);
     private Set detaAjusteInventarios = new HashSet(0);

    public Producto() {
    }

	
    public Producto(CatProducto catProducto, Compra compra, Seccion seccion, int codBarra, char estado) {
        this.catProducto = catProducto;
        this.compra = compra;
        this.seccion = seccion;
        this.codBarra = codBarra;
        this.estado = estado;
    }
    public Producto(CatProducto catProducto, Compra compra, Seccion seccion, int codBarra, char estado, Set detFacturas, Set detaAjusteInventarios) {
       this.catProducto = catProducto;
       this.compra = compra;
       this.seccion = seccion;
       this.codBarra = codBarra;
       this.estado = estado;
       this.detFacturas = detFacturas;
       this.detaAjusteInventarios = detaAjusteInventarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_producto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_producto_id_cat_producto", nullable=false)
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compra_id_compra", nullable=false)
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seccion_id_seccion", nullable=false)
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }

    
    @Column(name="cod_barra", nullable=false)
    public int getCodBarra() {
        return this.codBarra;
    }
    
    public void setCodBarra(int codBarra) {
        this.codBarra = codBarra;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getDetFacturas() {
        return this.detFacturas;
    }
    
    public void setDetFacturas(Set detFacturas) {
        this.detFacturas = detFacturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getDetaAjusteInventarios() {
        return this.detaAjusteInventarios;
    }
    
    public void setDetaAjusteInventarios(Set detaAjusteInventarios) {
        this.detaAjusteInventarios = detaAjusteInventarios;
    }




}


