package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * ProductoProveedor generated by hbm2java
 */
public class ProductoProveedor  implements java.io.Serializable {


     private Integer idProductoProveedor;
     private CatProducto catProducto;
     private Proveedor proveedor;
     private int catProductoMarcaIdMarca;

    public ProductoProveedor() {
    }

    public ProductoProveedor(CatProducto catProducto, Proveedor proveedor, int catProductoMarcaIdMarca) {
       this.catProducto = catProducto;
       this.proveedor = proveedor;
       this.catProductoMarcaIdMarca = catProductoMarcaIdMarca;
    }
   
    public Integer getIdProductoProveedor() {
        return this.idProductoProveedor;
    }
    
    public void setIdProductoProveedor(Integer idProductoProveedor) {
        this.idProductoProveedor = idProductoProveedor;
    }
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public int getCatProductoMarcaIdMarca() {
        return this.catProductoMarcaIdMarca;
    }
    
    public void setCatProductoMarcaIdMarca(int catProductoMarcaIdMarca) {
        this.catProductoMarcaIdMarca = catProductoMarcaIdMarca;
    }




}


