package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoProveedor generated by hbm2java
 */
@Entity
@Table(name="producto_proveedor"
    ,catalog="gasisw_bd1"
)
public class ProductoProveedor  implements java.io.Serializable {


     private Integer idProductoProveedor;
     private CatProducto catProducto;
     private Proveedor proveedor;
     private int catProductoMarcaIdMarca;

    public ProductoProveedor() {
    }

    public ProductoProveedor(CatProducto catProducto, Proveedor proveedor, int catProductoMarcaIdMarca) {
       this.catProducto = catProducto;
       this.proveedor = proveedor;
       this.catProductoMarcaIdMarca = catProductoMarcaIdMarca;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_producto_proveedor", unique=true, nullable=false)
    public Integer getIdProductoProveedor() {
        return this.idProductoProveedor;
    }
    
    public void setIdProductoProveedor(Integer idProductoProveedor) {
        this.idProductoProveedor = idProductoProveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CAT_PRODUCTO_id_cat_producto", nullable=false)
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROVEEDOR_id_proveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    
    @Column(name="CAT_PRODUCTO_MARCA_id_marca", nullable=false)
    public int getCatProductoMarcaIdMarca() {
        return this.catProductoMarcaIdMarca;
    }
    
    public void setCatProductoMarcaIdMarca(int catProductoMarcaIdMarca) {
        this.catProductoMarcaIdMarca = catProductoMarcaIdMarca;
    }




}


