package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private CatProducto catProducto;
     private Compra compra;
     private Seccion seccion;
     private int codBarra;
     private char estado;
     private Set detFacturas = new HashSet(0);
     private Set detaAjusteInventarios = new HashSet(0);

    public Producto() {
    }

	
    public Producto(CatProducto catProducto, Compra compra, Seccion seccion, int codBarra, char estado) {
        this.catProducto = catProducto;
        this.compra = compra;
        this.seccion = seccion;
        this.codBarra = codBarra;
        this.estado = estado;
    }
    public Producto(CatProducto catProducto, Compra compra, Seccion seccion, int codBarra, char estado, Set detFacturas, Set detaAjusteInventarios) {
       this.catProducto = catProducto;
       this.compra = compra;
       this.seccion = seccion;
       this.codBarra = codBarra;
       this.estado = estado;
       this.detFacturas = detFacturas;
       this.detaAjusteInventarios = detaAjusteInventarios;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public int getCodBarra() {
        return this.codBarra;
    }
    
    public void setCodBarra(int codBarra) {
        this.codBarra = codBarra;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getDetFacturas() {
        return this.detFacturas;
    }
    
    public void setDetFacturas(Set detFacturas) {
        this.detFacturas = detFacturas;
    }
    public Set getDetaAjusteInventarios() {
        return this.detaAjusteInventarios;
    }
    
    public void setDetaAjusteInventarios(Set detaAjusteInventarios) {
        this.detaAjusteInventarios = detaAjusteInventarios;
    }




}


