package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Municipio municipio;
     private String nombre;
     private String direccion;
     private String telefono;
     private String descripcion;
     private String nit;
     private Set productoProveedors = new HashSet(0);
     private Set ordenCompras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(Municipio municipio, String nombre, String direccion, String telefono) {
        this.municipio = municipio;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Proveedor(Municipio municipio, String nombre, String direccion, String telefono, String descripcion, String nit, Set productoProveedors, Set ordenCompras) {
       this.municipio = municipio;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.descripcion = descripcion;
       this.nit = nit;
       this.productoProveedors = productoProveedors;
       this.ordenCompras = ordenCompras;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public Set getProductoProveedors() {
        return this.productoProveedors;
    }
    
    public void setProductoProveedors(Set productoProveedors) {
        this.productoProveedors = productoProveedors;
    }
    public Set getOrdenCompras() {
        return this.ordenCompras;
    }
    
    public void setOrdenCompras(Set ordenCompras) {
        this.ordenCompras = ordenCompras;
    }




}


