package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol"
    ,catalog="gasisw_bd1"
)
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String tipoRol;
     private String descripcion;
     private String estado;
     private Set rolMenus = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String descripcion, String estado) {
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Rol(String tipoRol, String descripcion, String estado, Set rolMenus, Set usuarios) {
       this.tipoRol = tipoRol;
       this.descripcion = descripcion;
       this.estado = estado;
       this.rolMenus = rolMenus;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rol", unique=true, nullable=false)
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    
    @Column(name="tipo_rol", length=50)
    public String getTipoRol() {
        return this.tipoRol;
    }
    
    public void setTipoRol(String tipoRol) {
        this.tipoRol = tipoRol;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set getRolMenus() {
        return this.rolMenus;
    }
    
    public void setRolMenus(Set rolMenus) {
        this.rolMenus = rolMenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


