package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String tipoRol;
     private String descripcion;
     private String estado;
     private Set rolMenus = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String descripcion, String estado) {
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Rol(String tipoRol, String descripcion, String estado, Set rolMenus, Set usuarios) {
       this.tipoRol = tipoRol;
       this.descripcion = descripcion;
       this.estado = estado;
       this.rolMenus = rolMenus;
       this.usuarios = usuarios;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getTipoRol() {
        return this.tipoRol;
    }
    
    public void setTipoRol(String tipoRol) {
        this.tipoRol = tipoRol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getRolMenus() {
        return this.rolMenus;
    }
    
    public void setRolMenus(Set rolMenus) {
        this.rolMenus = rolMenus;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


