package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1



/**
 * RolMenu generated by hbm2java
 */
public class RolMenu  implements java.io.Serializable {


     private Integer idrolMenu;
     private Menu menu;
     private Rol rol;

    public RolMenu() {
    }

    public RolMenu(Menu menu, Rol rol) {
       this.menu = menu;
       this.rol = rol;
    }
   
    public Integer getIdrolMenu() {
        return this.idrolMenu;
    }
    
    public void setIdrolMenu(Integer idrolMenu) {
        this.idrolMenu = idrolMenu;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


