package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seccion generated by hbm2java
 */
@Entity
@Table(name="seccion"
    ,catalog="gasisw_bd1"
)
public class Seccion  implements java.io.Serializable {


     private Integer idSeccion;
     private Area area;
     private String nombre;
     private Set productos = new HashSet(0);

    public Seccion() {
    }

	
    public Seccion(Area area) {
        this.area = area;
    }
    public Seccion(Area area, String nombre, Set productos) {
       this.area = area;
       this.nombre = nombre;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_seccion", unique=true, nullable=false)
    public Integer getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(Integer idSeccion) {
        this.idSeccion = idSeccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="area_id_area", nullable=false)
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seccion")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


