package model;
// Generated 12-09-2015 09:53:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Submenu generated by hbm2java
 */
@Entity
@Table(name="submenu"
    ,catalog="gasisw_bd1"
)
public class Submenu  implements java.io.Serializable {


     private Integer idsubmenu;
     private Menu menu;
     private String nombreSubmenu;
     private String estado;
     private String url;

    public Submenu() {
    }

    public Submenu(Menu menu, String nombreSubmenu, String estado, String url) {
       this.menu = menu;
       this.nombreSubmenu = nombreSubmenu;
       this.estado = estado;
       this.url = url;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idsubmenu", unique=true, nullable=false)
    public Integer getIdsubmenu() {
        return this.idsubmenu;
    }
    
    public void setIdsubmenu(Integer idsubmenu) {
        this.idsubmenu = idsubmenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_idmenu", nullable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    
    @Column(name="nombre_submenu", nullable=false, length=150)
    public String getNombreSubmenu() {
        return this.nombreSubmenu;
    }
    
    public void setNombreSubmenu(String nombreSubmenu) {
        this.nombreSubmenu = nombreSubmenu;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="url", nullable=false, length=240)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


