package model;
// Generated 01-31-2016 04:09:44 PM by Hibernate Tools 4.3.1



/**
 * Submenu generated by hbm2java
 */
public class Submenu  implements java.io.Serializable {


     private Integer idsubmenu;
     private Menu menu;
     private String nombreSubmenu;
     private String estado;
     private String url;
     private String icono;

    public Submenu() {
    }

	
    public Submenu(Menu menu, String nombreSubmenu, String estado, String url) {
        this.menu = menu;
        this.nombreSubmenu = nombreSubmenu;
        this.estado = estado;
        this.url = url;
    }
    public Submenu(Menu menu, String nombreSubmenu, String estado, String url, String icono) {
       this.menu = menu;
       this.nombreSubmenu = nombreSubmenu;
       this.estado = estado;
       this.url = url;
       this.icono = icono;
    }
   
    public Integer getIdsubmenu() {
        return this.idsubmenu;
    }
    
    public void setIdsubmenu(Integer idsubmenu) {
        this.idsubmenu = idsubmenu;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getNombreSubmenu() {
        return this.nombreSubmenu;
    }
    
    public void setNombreSubmenu(String nombreSubmenu) {
        this.nombreSubmenu = nombreSubmenu;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }




}


