package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoFactura generated by hbm2java
 */
@Entity
@Table(name="tipo_factura"
    ,catalog="gasisw_bd1"
)
public class TipoFactura  implements java.io.Serializable {


     private Integer idTipoFactura;
     private Integer codigo;
     private String nombre;
     private Set facturas = new HashSet(0);

    public TipoFactura() {
    }

    public TipoFactura(Integer codigo, String nombre, Set facturas) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.facturas = facturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_factura", unique=true, nullable=false)
    public Integer getIdTipoFactura() {
        return this.idTipoFactura;
    }
    
    public void setIdTipoFactura(Integer idTipoFactura) {
        this.idTipoFactura = idTipoFactura;
    }

    
    @Column(name="codigo")
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nombre", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoFactura")
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


