package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoFactura generated by hbm2java
 */
public class TipoFactura  implements java.io.Serializable {


     private Integer idTipoFactura;
     private Integer codigo;
     private String nombre;
     private Set facturas = new HashSet(0);

    public TipoFactura() {
    }

    public TipoFactura(Integer codigo, String nombre, Set facturas) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.facturas = facturas;
    }
   
    public Integer getIdTipoFactura() {
        return this.idTipoFactura;
    }
    
    public void setIdTipoFactura(Integer idTipoFactura) {
        this.idTipoFactura = idTipoFactura;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


