package model;
// Generated 10-30-2016 07:08:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private int idTipoPago;
     private Character codigo;
     private String nombre;
     private Set pagos = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(int idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public TipoPago(int idTipoPago, Character codigo, String nombre, Set pagos) {
       this.idTipoPago = idTipoPago;
       this.codigo = codigo;
       this.nombre = nombre;
       this.pagos = pagos;
    }
   
    public int getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(int idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public Character getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Character codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


