package model;
// Generated 11-18-2015 05:01:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(name="tipo_pago"
    ,catalog="gasisw_bd1"
)
public class TipoPago  implements java.io.Serializable {


     private int idTipoPago;
     private Character codigo;
     private String nombre;
     private Set pagos = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(int idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public TipoPago(int idTipoPago, Character codigo, String nombre, Set pagos) {
       this.idTipoPago = idTipoPago;
       this.codigo = codigo;
       this.nombre = nombre;
       this.pagos = pagos;
    }
   
     @Id 

    
    @Column(name="id_tipo_pago", unique=true, nullable=false)
    public int getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(int idTipoPago) {
        this.idTipoPago = idTipoPago;
    }

    
    @Column(name="codigo", length=1)
    public Character getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Character codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nombre", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPago")
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


