package model;
// Generated 10-20-2015 11:47:24 PM by Hibernate Tools 4.3.1


import javax.annotation.PostConstruct;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioId generated by hbm2java
 */
@Embeddable
public class UsuarioId  implements java.io.Serializable {


     private int idUsuario;
     private int rolIdRol;
     
    public UsuarioId() {
        this.idUsuario = 0;
        this.rolIdRol = 0;
    }
    
    @PostConstruct
public void init() {
    this.idUsuario = 0;
    this.rolIdRol = 0;
}
    

  
    
    public UsuarioId(int idUsuario, int rolIdRol) {
       this.idUsuario = idUsuario;
       this.rolIdRol = rolIdRol;
    }
   


    @Column(name="id_usuario", nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


    @Column(name="rol_id_rol", nullable=false)
    public int getRolIdRol() {
        return this.rolIdRol;
    }
    
    public void setRolIdRol(int rolIdRol) {
        this.rolIdRol = rolIdRol;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getRolIdRol()==castOther.getRolIdRol());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getRolIdRol();
         return result;
   }   


}


