package model;
// Generated 10-20-2015 11:47:24 PM by Hibernate Tools 4.3.1


import javax.annotation.PostConstruct;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="gasisw_bd"
)
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Rol rol;
     private String usuario;
     private String contrasena;
     private String estado;

    public Usuario() {
        this.id = new UsuarioId();
        //this.rol = new Rol();
    }

    @PostConstruct
public void init() {
    this.id = new UsuarioId();
    //this.rol = new Rol();
}
    
    public Usuario(UsuarioId id,  Rol rol, String usuario, String contrasena, String estado) {
       this.id = id;
       this.rol = rol;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idUsuario", column=@Column(name="id_usuario", nullable=false) ), 
        @AttributeOverride(name="rolIdRol", column=@Column(name="rol_id_rol", nullable=false) ) } )
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol_id_rol", nullable=false, insertable=false, updatable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="usuario", nullable=false, length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasena", nullable=false, length=45)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


